"""Data naratif untuk mode contoh.

Teks di bawah ini fiktif. Nama media dipakai hanya sebagai label sumber
agar analis dapat membayangkan layar produksi. Tautan tidak mengarah
ke artikel sungguhan.
"""

from __future__ import annotations

# Kata inklusi per kategori. Pengguna dapat menambah dari UI.
KEYWORD_GROUPS = {
    "Institusi": [
        "Bank Indonesia",
        "BI",
        "KPw BI DKI Jakarta",
        "Bank Indonesia Jakarta",
        "Gubernur BI",
        "Deputi Gubernur BI",
        "RDG BI",
        "@bank_indonesia",
    ],
    "Kebijakan Moneter": [
        "BI-Rate",
        "suku bunga acuan",
        "inflasi",
        "nilai tukar",
        "rupiah",
        "intervensi valuta asing",
        "SRBI",
        "SBN",
        "likuiditas",
    ],
    "Sistem Pembayaran": [
        "QRIS",
        "BI-FAST",
        "rupiah digital",
        "Proyek Garuda",
        "QRIS antarnegara",
        "uang elektronik",
        "fintech",
        "kartu kredit",
        "GPN",
    ],
    "Makroprudensial": [
        "kredit perbankan",
        "KLM",
        "LTV",
        "stabilitas sistem keuangan",
        "kredit UMKM",
    ],
    "Pengedaran Uang": [
        "uang palsu",
        "penukaran uang",
        "uang layak edar",
        "kas keliling",
        "uang baru",
    ],
    "Isu Lokal Jakarta": [
        "ekonomi Jakarta",
        "inflasi Jakarta",
        "UMKM Jakarta",
        "harga pangan Jakarta",
        "TPID DKI",
    ],
    "Isu Sensitif": [
        "hoaks BI",
        "penipuan mengatasnamakan BI",
        "kebocoran data",
        "independensi BI",
        "burden sharing",
        "kritik kebijakan",
        "demo",
        "gangguan sistem pembayaran",
    ],
    "Valuta asing": ["money changer", "dolar", "kupva BB", "tukar rupiah"],
    "Regulasi/Industri": ["PJP", "penyelenggara sistem pembayaran"],
    "Dompet digital/Fintech": ["flip", "GoPay", "DANA", "OVO"],
}

EXCLUSIONS = ["lowongan", "karir", "loker", "kode promo", "iklan baris"]

SAVED_QUERIES = [
    (
        "Paket institusi",
        '("Bank Indonesia" OR "KPw BI" OR QRIS OR "BI-FAST" OR "BI-Rate" OR rupiah) AND NOT (lowongan OR karir OR loker)',
    ),
    (
        "Paket isu sensitif",
        'hoaks OR penipuan OR "kebocoran data" OR "burden sharing" OR demo OR "gangguan"',
    ),
    (
        "Paket valuta dan pembayaran",
        '("money changer" OR dolar OR "kupva BB" OR "tukar rupiah" OR PJP OR "penyelenggara sistem pembayaran" OR flip OR GoPay OR DANA OR OVO) AND NOT (lowongan OR karir OR loker)',
    ),
]

USERS = [
    ("admin", "Admin Sistem", "admin", "admin123"),
    ("analis", "Analis Media", "analis", "analis123"),
    ("pimpinan", "Pejabat Pimpinan", "pimpinan", "pimpinan123"),
]

# day_start / day_end: berapa hari ke belakang konten isu ini tersebar.
STORIES = [
    {
        "code": "ISS-HOAX",
        "title": "Hoaks undian dan rekrutmen mengatasnamakan Bank Indonesia",
        "category": "Hoaks/Penipuan",
        "stance": "downside",
        "sentiment": "negatif",
        "impact_level": "tinggi",
        "spread_velocity": 92,
        "status": "dieskalasi",
        "pic": "Analis Media",
        "is_critical": True,
        "is_kpw": False,
        "spike_detected": True,
        "day_start": 3,
        "day_end": 0,
        "has_public_figure": False,
        "summary": "Unggahan undian berhadiah dan rekrutmen fiktif memakai nama Bank Indonesia menyebar di media sosial dan mulai diangkat media.",
        "ai_what": "Beredar unggahan undian berhadiah dan tautan rekrutmen pegawai yang mengatasnamakan Bank Indonesia. Pola pesannya meminta data pribadi atau pembayaran administrasi.",
        "ai_who": "Akun yang tidak terverifikasi di Facebook, TikTok, dan X, diteruskan warga, lalu diangkat Detik, Kompas, dan Antara sebagai imbauan.",
        "ai_sentiment": "Dominan negatif dan khawatir. Sebagian percakapan sudah bersifat korektif setelah media mengingatkan bahwa itu penipuan.",
        "ai_impact": "Risiko langsung ada pada masyarakat yang tertipu, ditambah erosi kepercayaan terhadap kanal resmi BI bila klarifikasi terlambat.",
        "ai_recommendation": "Saran komunikasi: tayangkan klarifikasi singkat di kanal resmi BI dan KPw DKI dalam dua jam, siapkan teks yang mudah dibagikan ulang, dan catat varian narasi baru. Ini bukan keputusan kebijakan.",
        "news": [
            (
                "Waspada hoaks undian berhadiah mengatasnamakan Bank Indonesia",
                "Sejumlah unggahan menjanjikan hadiah puluhan juta dengan memakai nama Bank Indonesia. Masyarakat diminta tidak mengklik tautan dan tidak mengirim data pribadi. Kanal resmi tidak pernah menyelenggarakan undian semacam itu.",
            ),
            (
                "Modus rekrutmen palsu Bank Indonesia beredar di media sosial",
                "Pelamar diminta membayar biaya administrasi melalui rekening pribadi. Bank Indonesia mengingatkan seluruh rekrutmen hanya diumumkan di kanal resmi dan tidak memungut biaya.",
            ),
            (
                "Antara imbau warga abaikan tautan berhadiah berkedok Bank Indonesia",
                "Imbauan disampaikan setelah laporan warga Jakarta meningkat sejak akhir pekan. Kepolisian setempat disebut mulai menerima aduan penipuan.",
            ),
            (
                "Kompas cek fakta: undian Bank Indonesia yang viral tidak benar",
                "Tidak ada pengumuman resmi tentang undian. Logo dan kop surat pada unggahan itu hasil rekayasa. Warga yang sudah mengisi formulir disarankan mengganti kata sandi akun yang sama.",
            ),
        ],
        "social": [
            ("facebook", "Warga Jakarta", "@warga_jakarta_08", "Yang di grup RT pada sebar undian BI hadiah 50 juta. Jangan diklik, ini pola penipuan. #HoaksBI #BankIndonesia", False),
            ("tiktok", "Cek Fakta Warga", "@cekfakta_warga", "Lagi ramai rekrutmen pegawai Bank Indonesia minta biaya di muka. Itu hoaks. Cek pengumuman resmi, jangan isi data. #Hoaks #Penipuan", False),
            ("x", "Akun Mirip 21", "@akun_serupa_21", "INFO CEPAT lowongan Bank Indonesia, daftar di link ini sebelum ditutup malam ini. Hadiah dan gaji besar.", True),
            ("x", "Akun Mirip 22", "@akun_serupa_22", "INFO CEPAT undian resmi Bank Indonesia cair hari ini, isi data rekening untuk klaim hadiah.", True),
            ("threads", "Ekonomi Terbuka", "@ekonomi_terbuka", "Hoaks rekrutmen BI ini bahaya karena meniru bahasa pengumuman resmi. Perlu klarifikasi yang sangat pendek dan mudah di-forward.", False),
            ("forum", "Komunitas Publik", "komunitas_jakarta", "Utas forum: ada yang hampir transfer ke rekening penipuan berkedok Bank Indonesia. Mohon disebar imbauannya.", False),
        ],
    },
    {
        "code": "ISS-RUPIAH",
        "title": "Rupiah melemah di tengah penguatan dolar AS",
        "category": "Rupiah/Kurs",
        "stance": "downside",
        "sentiment": "negatif",
        "impact_level": "tinggi",
        "spread_velocity": 74,
        "status": "ditinjau",
        "pic": "Analis Media",
        "is_critical": True,
        "is_kpw": False,
        "spike_detected": True,
        "day_start": 8,
        "day_end": 0,
        "has_public_figure": True,
        "summary": "Nilai tukar rupiah berada di bawah tekanan. Percakapan publik menyorot intervensi dan komunikasi Bank Indonesia.",
        "ai_what": "Rupiah melemah terhadap dolar AS selama beberapa hari. Pemberitaan menyorot arus modal global, selisih suku bunga, dan kesiapan intervensi valuta asing.",
        "ai_who": "Media pasar (Kontan, CNBC Indonesia, Bloomberg Technoz), analis pasar di X, dan kutipan bernada resmi dari Gubernur BI tanpa detail operasi.",
        "ai_sentiment": "Cenderung negatif di media sosial, lebih datar di media ekonomi yang menekankan langkah stabilisasi.",
        "ai_impact": "Persepsi stabilitas nilai tukar berpengaruh pada ekspektasi inflasi dan kepercayaan pelaku usaha. Belum ada bukti gangguan kebijakan yang berjalan.",
        "ai_recommendation": "Saran komunikasi: gunakan satu kalimat jangkar tentang komitmen stabilitas nilai tukar, hindari angka operasi intervensi, dan arahkan kutipan ke pernyataan resmi yang sudah tayang. Saran ini untuk narasi, bukan instruksi kebijakan moneter.",
        "news": [
            (
                "Rupiah melemah, pasar menanti komunikasi nilai tukar Bank Indonesia",
                "Rupiah bergerak melemah terhadap dolar AS. Analis menyebut tekanan berasal dari penguatan dolar global. Bank Indonesia menegaskan komitmen menjaga stabilitas nilai tukar rupiah.",
            ),
            (
                "Kontan: volatilitas rupiah naik, importir Jakarta mulai waspada",
                "Pelaku impor di Jakarta mengeluhkan ketidakpastian kurs. Mereka menunggu arah intervensi valuta asing dan likuiditas valas di pasar.",
            ),
            (
                "Bloomberg Technoz catat rupiah tertinggal dari mata uang kawasan",
                "Pergerakan rupiah lebih lemah dibanding sejumlah mata uang tetangga pada sesi siang. Ekonom mengingatkan agar ekspektasi inflasi tetap dijaga.",
            ),
            (
                "Gubernur BI: stabilitas nilai tukar tetap menjadi prioritas",
                "Gubernur BI menyampaikan Bank Indonesia akan berada di pasar bila tekanan terhadap rupiah berlebihan. Pernyataan itu menenangkan sebagian pelaku, tetapi komentar publik masih khawatir.",
            ),
        ],
        "social": [
            ("x", "Analis Pasar", "@ekonomi_terbuka", "Rupiah nyungsep lagi hari ini. Gak nyaman kalau komunikasi nilai tukar telat. #Rupiah #BankIndonesia", False),
            ("x", "Warga Jakarta", "@warga_jakarta_08", "Dolar naik terus, harga barang di toko Jakarta nanti ikut naik. BI jangan diam saja.", False),
            ("instagram", "UMKM Jakarta", "@umkm_jakarta", "Buat yang impor bahan baku, kurs rupiah yang melemah bikin modal nambah. Semoga nilai tukar cepat stabil.", False),
            ("youtube", "Kanal Ekonomi", "@kanal_ekonomi_id", "Video: kenapa rupiah melemah dan apa arti suku bunga acuan bagi pengusaha.", False),
            ("threads", "Cek Fakta Warga", "@cekfakta_warga", "Jangan termakan unggahan yang bilang BI kehabisan amunisi valas. Itu klaim tanpa data resmi.", False),
        ],
    },
    {
        "code": "ISS-RATE",
        "title": "BI menahan BI-Rate di 5,75 persen",
        "category": "Kebijakan Moneter",
        "stance": "upside",
        "sentiment": "positif",
        "impact_level": "tinggi",
        "spread_velocity": 60,
        "status": "ditinjau",
        "pic": "Analis Media",
        "is_critical": False,
        "is_kpw": False,
        "spike_detected": False,
        "day_start": 16,
        "day_end": 9,
        "has_public_figure": True,
        "summary": "Rapat Dewan Gubernur menahan suku bunga acuan. Pemberitaan menilai keputusan memberi kepastian dan menjaga inflasi tetap terkendali.",
        "ai_what": "Rapat Dewan Gubernur Bank Indonesia memutuskan menahan BI-Rate pada 5,75 persen. Alasan yang dikutip media adalah inflasi yang terkendali dan upaya menjaga daya tarik rupiah.",
        "ai_who": "Media arus utama, ekonom pasar, dan pernyataan Gubernur BI serta Deputi Gubernur BI.",
        "ai_sentiment": "Mayoritas positif hingga netral. Kritik muncul pada kelompok yang berharap bunga kredit segera turun.",
        "ai_impact": "Keputusan dipahami pasar. Ruang persepsi yang perlu dijaga adalah kaitan antara BI-Rate dan bunga kredit perbankan, agar tidak disederhanakan berlebihan.",
        "ai_recommendation": "Saran komunikasi: siapkan penjelasan awam mengapa suku bunga acuan ditahan, dan bedakan dengan bunga kredit bank. Cocok dipakai ulang oleh KPw saat edukasi publik di Jakarta.",
        "news": [
            (
                "BI tahan BI-Rate di 5,75 persen, inflasi diperkirakan tetap terkendali",
                "Rapat Dewan Gubernur Bank Indonesia menahan suku bunga acuan. Keputusan dinilai memberi kepastian bagi pasar keuangan dan mendukung stabilitas rupiah.",
            ),
            (
                "CNBC Indonesia: pasar menyambut keputusan BI yang sesuai ekspektasi",
                "Mayoritas ekonom yang disurvei telah memperkirakan BI-Rate tidak berubah. Imbal hasil SBN relatif tenang setelah pengumuman.",
            ),
            (
                "Deputi Gubernur BI jelaskan bauran kebijakan moneter dan likuiditas",
                "Selain suku bunga, Bank Indonesia menjaga likuiditas melalui SRBI dan operasi moneter. Langkah ini bertujuan menopang stabilitas tanpa menahan kredit yang sehat.",
            ),
            (
                "Tempo: pelaku usaha harap bunga kredit ikut mereda",
                "Sebagian asosiasi usaha mengapresiasi kepastian BI-Rate, tetapi tetap meminta perbankan menyesuaikan bunga kredit UMKM secara bertahap.",
            ),
        ],
        "social": [
            ("x", "Ekonomi Terbuka", "@ekonomi_terbuka", "Keputusan tahan BI-Rate ini sesuai prakiraan. Yang penting inflasi tetap terkendali dan rupiah tidak liar. #BIRate", False),
            ("x", "Warga Jakarta", "@warga_jakarta_08", "Suku bunga acuan ditahan. Kapan bunga KPR saya ikut turun? Mohon dijelaskan dengan bahasa awam.", False),
            ("youtube", "Kanal Ekonomi", "@kanal_ekonomi_id", "Ringkas RDG BI: BI-Rate 5,75 persen, inflasi, dan arti keputusan ini bagi rumah tangga.", False),
            ("instagram", "KPw BI DKI", "@kpwbi_dki", "KPw BI DKI Jakarta mengulas keputusan BI-Rate dalam bahasa yang lebih mudah untuk pelaku usaha Jakarta. #BIRate #KPwDKI", False),
            ("forum", "Komunitas Publik", "komunitas_jakarta", "Utas: adakah dampak langsung BI-Rate ke cicilan? Yang punya sumber resmi boleh tempel.", False),
        ],
    },
    {
        "code": "ISS-QRIS",
        "title": "Perluasan QRIS antarnegara di ASEAN",
        "category": "Sistem Pembayaran",
        "stance": "upside",
        "sentiment": "positif",
        "impact_level": "sedang",
        "spread_velocity": 66,
        "status": "ditangani",
        "pic": "Tim Komunikasi",
        "is_critical": False,
        "is_kpw": True,
        "spike_detected": False,
        "day_start": 10,
        "day_end": 1,
        "has_public_figure": False,
        "summary": "Perluasan QRIS antarnegara mendapat sambutan positif, termasuk dari pelaku wisata dan UMKM Jakarta.",
        "ai_what": "Bank Indonesia memperluas jalur QRIS antarnegara. Pemberitaan menyorot kemudahan pembayaran bagi wisatawan dan UMKM di Jakarta.",
        "ai_who": "Media ekonomi, akun UMKM, dan kanal KPw BI DKI Jakarta.",
        "ai_sentiment": "Positif. Pertanyaan yang muncul bersifat teknis: biaya, kecepatan dana, dan keandalan koneksi.",
        "ai_impact": "Peluang memperkuat persepsi BI pada sistem pembayaran. Risiko kecil ada bila ekspektasi pedagang lebih tinggi daripada kesiapan mitra bank.",
        "ai_recommendation": "Saran komunikasi: tampilkan satu contoh transaksi yang berhasil, sebut batas yang memang belum tersedia, dan arahkan pedagang ke edukasi KPw. Jangan menjanjikan fitur yang belum diluncurkan.",
        "news": [
            (
                "QRIS antarnegara meluas, pelaku wisata Jakarta sambut positif",
                "Wisatawan dapat membayar pedagang Jakarta memakai QRIS tanpa menukar uang tunai. Bank Indonesia menyebut perluasan ini bagian dari konektivitas sistem pembayaran ASEAN.",
            ),
            (
                "Bisnis.com: UMKM kuliner Jakarta mulai terima pembayaran lintas negara",
                "Beberapa pedagang di Jakarta Pusat mencoba QRIS antarnegara. Mereka menyebut pencatatan penjualan menjadi lebih rapi.",
            ),
            (
                "Liputan6 ulas cara kerja QRIS bagi pedagang kecil",
                "Artikel menjelaskan perbedaan QRIS, uang elektronik, dan kartu. Nada tulisan mendukung literasi, dengan catatan koneksi internet masih menentukan kelancaran.",
            ),
            (
                "Antara: Bank Indonesia perluas QRIS antarnegara secara bertahap",
                "Perluasan dilakukan bertahap agar keandalan sistem pembayaran tetap terjaga. GPN tetap menjadi tulang punggung transaksi domestik.",
            ),
        ],
        "social": [
            ("instagram", "UMKM Jakarta", "@umkm_jakarta", "Pembeli dari luar negeri bisa scan QRIS di warung. Transaksi jadi mudah dan tercatat. Terima kasih edukasinya. #QRIS #UMKMJakarta", False),
            ("tiktok", "UMKM Jakarta", "@umkm_jakarta", "Tutorial singkat: cara terima QRIS antarnegara tanpa panik. Sudah kami coba di Jakarta Pusat.", False),
            ("x", "Ekonomi Terbuka", "@ekonomi_terbuka", "QRIS lintas negara ini contoh kebijakan yang langsung terasa. Yang perlu dijaga cuma kecepatan settlement. #QRIS", False),
            ("youtube", "KPw BI DKI", "@kpwbi_dki", "KPw BI DKI Jakarta: tanya jawab QRIS bersama pedagang Tanah Abang.", False),
            ("threads", "Warga Jakarta", "@warga_jakarta_08", "Akhirnya bayar ke UMKM pakai QRIS lebih familiar. Semoga biaya merchant tetap ramah.", False),
        ],
    },
    {
        "code": "ISS-BIFAST",
        "title": "Gangguan singkat layanan BI-FAST",
        "category": "Sistem Pembayaran",
        "stance": "downside",
        "sentiment": "negatif",
        "impact_level": "sedang",
        "spread_velocity": 84,
        "status": "ditangani",
        "pic": "Tim Komunikasi",
        "is_critical": False,
        "is_kpw": False,
        "spike_detected": True,
        "day_start": 7,
        "day_end": 5,
        "has_public_figure": False,
        "summary": "Layanan BI-FAST sempat terganggu. Keluhan nasabah cepat naik, kemudian mereda setelah layanan pulih dan klarifikasi tayang.",
        "ai_what": "Transfer BI-FAST sempat gagal pada sebagian nasabah selama jendela waktu yang terbatas. Layanan kemudian dilaporkan pulih.",
        "ai_who": "Nasabah di X dan Instagram, media teknologi, serta klarifikasi industri pembayaran.",
        "ai_sentiment": "Negatif pada jam gangguan, bergeser ke netral setelah ada konfirmasi pemulihan. Sarkasme muncul pada unggahan yang memuji layanan sambil menyebut transaksi gagal.",
        "ai_impact": "Kepercayaan pada sistem pembayaran sensitif terhadap gangguan, meski singkat. Isu ini tidak menyentuh kebijakan moneter.",
        "ai_recommendation": "Saran komunikasi: bila kejadian serupa terulang, umumkan status layanan, perkiraan pemulihan, dan saluran pengaduan dalam satu kartu informasi. Jangan berspekulasi soal penyebab sebelum ada pemeriksaan.",
        "news": [
            (
                "BI-FAST sempat gangguan, sebagian transfer tertunda",
                "Nasabah melaporkan transfer BI-FAST tidak kunjung masuk. Bank Indonesia dan industri pembayaran menyatakan tim sedang memulihkan layanan sistem pembayaran.",
            ),
            (
                "CNN Indonesia: keluhan BI-FAST ramai di media sosial",
                "Unggahan keluhan naik dalam hitungan jam. Tidak ada laporan kehilangan dana yang terkonfirmasi pada pemberitaan awal.",
            ),
            (
                "Layanan BI-FAST dilaporkan pulih, antrean transaksi dikosongkan",
                "Setelah pemulihan, transaksi yang tertunda diproses bertahap. Media mengingatkan nasabah memeriksa mutasi sebelum mengirim ulang.",
            ),
            (
                "Kontan catat kepercayaan pembayaran instan jadi sorotan",
                "Gangguan singkat tetap menjadi ujian reputasi karena BI-FAST sudah menjadi kebiasaan harian. Analis meminta komunikasi status yang lebih cepat.",
            ),
        ],
        "social": [
            ("x", "Warga Jakarta", "@warga_jakarta_08", "BI-FAST error terus dari tadi siang. Uang menggantung, ini gangguan sistem pembayaran yang bikin panik.", False),
            ("x", "Akun Mirip 21", "@akun_serupa_21", "Makasih ya BI, BI-FAST-nya mantap sekali anjlok. Transfer gak jalan.", True),
            ("instagram", "Cek Fakta Warga", "@cekfakta_warga", "Lagi ramai keluhan BI-FAST. Tunggu kanal resmi sebelum percaya unggahan yang bilang data bocor. Belum ada bukti kebocoran.", False),
            ("tiktok", "Kanal Ekonomi", "@kanal_ekonomi_id", "Jangan kirim ulang transfer BI-FAST sebelum cek mutasi. Gangguan ini sudah diakui, layanan dipulihkan.", False),
            ("facebook", "Komunitas Publik", "komunitas_jakarta", "Di grup keluarga banyak yang transfernya tertunda. Ada yang sudah berhasil masuk lagi.", False),
        ],
    },
    {
        "code": "ISS-BURDEN",
        "title": "Perdebatan burden sharing dan independensi BI",
        "category": "Reputasi/Kelembagaan",
        "stance": "downside",
        "sentiment": "negatif",
        "impact_level": "sedang",
        "spread_velocity": 36,
        "status": "baru",
        "pic": "",
        "is_critical": False,
        "is_kpw": False,
        "spike_detected": False,
        "day_start": 20,
        "day_end": 12,
        "has_public_figure": True,
        "summary": "Artikel opini dan utas panjang membahas burden sharing serta batas independensi Bank Indonesia. Volumenya tidak meledak, tetapi nadanya tajam.",
        "ai_what": "Muncul kembali perdebatan publik tentang burden sharing antara Bank Indonesia dan pemerintah, serta arti independensi BI dalam kebijakan moneter.",
        "ai_who": "Kolom opini media, ekonom, dan akun komentator. Bukan percakapan massal.",
        "ai_sentiment": "Negatif hingga kritis, dengan sebagian suara yang membela kerangka kelembagaan yang ada.",
        "ai_impact": "Isu ini menyentuh reputasi kelembagaan lebih daripada operasional harian. Dapat diangkat di forum kebijakan bila narasinya melebar ke media arus utama.",
        "ai_recommendation": "Saran komunikasi: siapkan catatan tanya-jawab yang membedakan fakta hukum dan opini. Jangan menanggapi setiap utas. Bila media tier-1 meminta kutipan, arahkan ke juru bicara pusat.",
        "news": [
            (
                "Opini: burden sharing dan batas independensi Bank Indonesia",
                "Kolom ini mengkritisi skema burden sharing dan menanyakan apakah independensi BI tetap terjaga. Tulisan bersifat pendapat, bukan pengumuman kebijakan.",
            ),
            (
                "Ekonom bedah ulang hubungan kebijakan moneter dan fiskal",
                "Perdebatan mengulas koordinasi yang sehat versus tekanan terhadap bank sentral. Narasumber berbeda pendapat tentang risiko reputasi jangka panjang.",
            ),
            (
                "Tempo catat kritik kebijakan di kalangan akademisi",
                "Kritik terfokus pada komunikasi beban bersama, bukan pada operasi pasar terbuka. Volume pemberitaan masih terbatas.",
            ),
            (
                "Kompas tampilkan dua sudut pandang tentang independensi BI",
                "Satu pihak menekankan akuntabilitas, pihak lain menekankan bahwa koordinasi tidak otomatis mengurangi independensi. Artikel relatif berimbang.",
            ),
        ],
        "social": [
            ("x", "Ekonomi Terbuka", "@ekonomi_terbuka", "Utas burden sharing ini perlu dibaca pelan. Kritiknya soal independensi BI, bukan soal layanan harian.", False),
            ("forum", "Komunitas Publik", "komunitas_jakarta", "Utas opini: apakah bank sentral masih independen? Mohon sumber primer, jangan hanya tangkapan layar.", False),
            ("threads", "Kanal Ekonomi", "@kanal_ekonomi_id", "Kritik kebijakan boleh, tapi jangan dicampur dengan hoaks kebocoran data. Dua isu itu berbeda.", False),
            ("youtube", "Kanal Ekonomi", "@kanal_ekonomi_id", "Diskusi studio: apa arti independensi bank sentral bagi publik awam.", False),
            ("x", "Warga Jakarta", "@warga_jakarta_08", "Saya tidak paham burden sharing, tapi judulnya bikin khawatir. Tolong ada penjelasan yang tidak penuh istilah.", False),
        ],
    },
    {
        "code": "ISS-PANGAN",
        "title": "Harga pangan dan inflasi Jakarta",
        "category": "Ekonomi Jakarta",
        "stance": "downside",
        "sentiment": "negatif",
        "impact_level": "sedang",
        "spread_velocity": 58,
        "status": "ditinjau",
        "pic": "Analis Media",
        "is_critical": False,
        "is_kpw": True,
        "spike_detected": False,
        "day_start": 6,
        "day_end": 0,
        "has_public_figure": False,
        "summary": "Kenaikan harga beberapa komoditas pangan di Jakarta menjadi bahan percakapan, dikaitkan dengan inflasi daerah dan peran TPID DKI.",
        "ai_what": "Harga cabai, beras, dan minyak goreng di sejumlah pasar Jakarta bergerak naik. Media lokal mengaitkannya dengan inflasi Jakarta dan pembahasan TPID DKI.",
        "ai_who": "Media lokal Jakarta, pedagang pasar, dan unggahan warga. KPw disebut dalam konteks edukasi dan pemantauan, bukan sebagai penentu harga.",
        "ai_sentiment": "Negatif karena tekanan harga, dengan nada yang lebih datar pada berita yang memuat upaya pasokan.",
        "ai_impact": "Inflasi pangan mempengaruhi persepsi masyarakat terhadap stabilitas harga, meskipun instrumen BI bukan pengendali harga eceran.",
        "ai_recommendation": "Saran komunikasi KPw: jelaskan peran TPID dan batas mandat BI, tampilkan data harga yang sudah publik, dan hindari janji harga turun. Koordinasi narasi dengan pemda bila akan ada pernyataan bersama.",
        "news": [
            (
                "Harga pangan Jakarta naik, TPID DKI bahas pasokan",
                "Harga beberapa bahan pokok di pasar induk bergerak naik. TPID DKI membahas kelancaran pasokan. Inflasi Jakarta menjadi perhatian bersama pemerintah daerah dan Bank Indonesia.",
            ),
            (
                "Warta Kota: pedagang Jatinegara keluhkan harga cabai",
                "Pedagang menyebut pasokan belum merata. Warga mengaitkan kenaikan ini dengan inflasi harian di Jakarta Timur.",
            ),
            (
                "Berita Jakarta: ekonomi Jakarta masih ditopang konsumsi, pangan jadi sorotan",
                "Konsumsi rumah tangga menopang aktivitas, tetapi kenaikan harga pangan menekan daya beli kelompok berpendapatan tetap.",
            ),
            (
                "KPw BI DKI catat pemantauan harga di pasar tradisional",
                "KPw BI DKI Jakarta melakukan pencatatan harga bersama mitra daerah. Hasilnya dipakai sebagai masukan inflasi, bukan sebagai penetapan harga.",
            ),
        ],
        "social": [
            ("instagram", "Warga Jakarta", "@warga_jakarta_08", "Belanja di pasar Jakarta Timur makin berat. Inflasi pangan ini terasa di dapur.", False),
            ("tiktok", "UMKM Jakarta", "@umkm_jakarta", "Harga bahan baku warung naik. UMKM Jakarta lagi hitung ulang porsi.", False),
            ("x", "Ekonomi Terbuka", "@ekonomi_terbuka", "Inflasi Jakarta bulan ini kemungkinan didorong pangan, bukan permintaan yang meledak. TPID DKI perlu terlihat bekerja.", False),
            ("facebook", "Komunitas Publik", "komunitas_jakarta", "Di grup ibu-ibu, minyak goreng dan cabai jadi keluhan. Ada yang lihat operasi pasar?", False),
            ("threads", "KPw BI DKI", "@kpwbi_dki", "KPw BI DKI ikut pemantauan harga pangan di pasar. Data ini masukan inflasi daerah, bukan patokan harga jual.", False),
        ],
        "locations": ["Jakarta Timur", "Jakarta Pusat", "Jakarta Utara", "Jakarta Barat"],
    },
    {
        "code": "ISS-UMKM",
        "title": "Percepatan adopsi QRIS oleh UMKM Jakarta",
        "category": "Kegiatan KPw DKI",
        "stance": "upside",
        "sentiment": "positif",
        "impact_level": "sedang",
        "spread_velocity": 48,
        "status": "ditangani",
        "pic": "Tim Komunikasi",
        "is_critical": False,
        "is_kpw": True,
        "spike_detected": False,
        "day_start": 9,
        "day_end": 0,
        "has_public_figure": False,
        "summary": "Kegiatan KPw BI DKI mendorong UMKM Jakarta memakai QRIS. Engagement kanal resmi naik dan testimoni pedagang cenderung positif.",
        "ai_what": "KPw BI DKI Jakarta menggelar serangkaian edukasi QRIS dan pembiayaan bagi UMKM di beberapa kota administrasi.",
        "ai_who": "Kanal resmi KPw, peserta UMKM, dan liputan media lokal.",
        "ai_sentiment": "Positif. Masukan yang berulang adalah biaya merchant dan kebutuhan pendampingan setelah acara.",
        "ai_impact": "Ini ukuran efektivitas kampanye kehumasan KPw. Peluang memperkuat citra BI yang dekat dengan usaha kecil Jakarta.",
        "ai_recommendation": "Saran komunikasi: lanjutkan testimoni pedagang asli, tampilkan angka peserta yang bisa diaudit, dan siapkan jawaban standar tentang biaya. Ukur ulang engagement tujuh hari setelah unggahan.",
        "news": [
            (
                "KPw BI DKI Jakarta perluas edukasi QRIS bagi UMKM",
                "Ratusan pelaku usaha mengikuti sesi pendampingan QRIS dan pencatatan keuangan sederhana. Peserta menyebut transaksi menjadi lebih mudah.",
            ),
            (
                "Berita Jakarta liput pelatihan UMKM di Jakarta Selatan",
                "Pelatihan KPw BI DKI mencakup QRIS, uang elektronik, dan cara mengenali penipuan berkedok lembaga keuangan.",
            ),
            (
                "UMKM binaan mulai pisahkan rekening usaha setelah edukasi KPw",
                "Sebagian peserta melaporkan pencatatan penjualan membaik. Mereka meminta sesi lanjutan tentang kredit UMKM.",
            ),
            (
                "Liputan6: literasi keuangan KPw menyasar pasar tradisional",
                "Kegiatan berlangsung di pasar, bukan hanya di ruang seminar. Pendekatan ini dinilai lebih mudah dijangkau pedagang.",
            ),
        ],
        "social": [
            ("instagram", "KPw BI DKI", "@kpwbi_dki", "Hari ini di Pasar Mayestik: edukasi QRIS untuk UMKM Jakarta. Terima kasih pedagang yang sudah hadir. #KPwDKI #QRIS", False),
            ("instagram", "UMKM Jakarta", "@umkm_jakarta", "Baru pasang QRIS setelah didampingi KPw BI DKI. Pembeli senang, saya juga tidak perlu menyiapkan uang kembalian terus.", False),
            ("x", "KPw BI DKI", "@kpwbi_dki", "Ringkasan kegiatan: literasi sistem pembayaran dan waspada penipuan mengatasnamakan lembaga. Materi bisa diminta ke kanal resmi.", False),
            ("youtube", "KPw BI DKI", "@kpwbi_dki", "Cuplikan pelatihan UMKM Jakarta Barat: dari QRIS sampai catat untung harian.", False),
            ("tiktok", "UMKM Jakarta", "@umkm_jakarta", "POV pedagang pertama kali terima QRIS. Lebih cepat dari yang saya kira.", False),
        ],
        "locations": ["Jakarta Selatan", "Jakarta Barat", "Jakarta Pusat", "Jakarta Utara"],
    },
    {
        "code": "ISS-KAS",
        "title": "Kas keliling uang layak edar di Jakarta",
        "category": "Pengedaran Uang",
        "stance": "upside",
        "sentiment": "positif",
        "impact_level": "rendah",
        "spread_velocity": 34,
        "status": "selesai",
        "pic": "Tim Komunikasi",
        "is_critical": False,
        "is_kpw": True,
        "spike_detected": False,
        "day_start": 8,
        "day_end": 2,
        "has_public_figure": False,
        "summary": "Layanan kas keliling KPw BI DKI untuk penukaran uang layak edar mendapat liputan positif dan antrean yang tertib.",
        "ai_what": "KPw BI DKI Jakarta menggelar kas keliling penukaran uang lusuh dan uang tidak layak edar di beberapa wilayah.",
        "ai_who": "Media lokal dan warga yang mengunggah pengalaman antre.",
        "ai_sentiment": "Positif. Masukan operasional: antrean pagi dan kebutuhan informasi lokasi sehari sebelumnya.",
        "ai_impact": "Dampak kebijakan kecil, dampak persepsi layanan publik cukup baik. Cocok sebagai bukti kehadiran KPw.",
        "ai_recommendation": "Saran komunikasi: umumkan jadwal lebih awal dan ingatkan ciri uang layak edar. Tidak perlu dikaitkan dengan isu moneter.",
        "news": [
            (
                "KPw BI DKI gelar kas keliling di Pasar Induk Kramat Jati",
                "Warga menukar uang lusuh dengan uang layak edar. Petugas juga menjelaskan cara mengenali uang palsu tanpa merusak uang asli.",
            ),
            (
                "Penukaran uang di Jakarta Utara berjalan tertib",
                "Antrean bergerak sejak pagi. KPw BI DKI menyediakan nomor urut dan imbauan agar masyarakat tidak menggunakan jasa calo.",
            ),
            (
                "Warta Kota: pedagang sambut layanan kas keliling",
                "Pedagang membutuhkan pecahan kecil menjelang akhir pekan. Layanan ini mengurangi keresahan uang tidak layak edar.",
            ),
            (
                "Antara: KPw ingatkan penukaran uang tidak dipungut biaya",
                "Tidak ada biaya pada kas keliling resmi. Imbauan disampaikan untuk menutup modus penipuan yang meminta ongkos antar.",
            ),
        ],
        "social": [
            ("instagram", "KPw BI DKI", "@kpwbi_dki", "Kas keliling hari ini melayani penukaran uang layak edar. Gratis, tanpa calo. #KasKeliling #KPwDKI", False),
            ("facebook", "Warga Jakarta", "@warga_jakarta_08", "Baru tukar uang lusuh di kas keliling KPw. Petugasnya jelas dan antreannya rapi.", False),
            ("x", "Cek Fakta Warga", "@cekfakta_warga", "Pengingat: penukaran uang Bank Indonesia tidak minta biaya admin. Yang minta transfer dulu itu bukan petugas.", False),
            ("tiktok", "KPw BI DKI", "@kpwbi_dki", "Ciri uang layak edar, dijelaskan 30 detik.", False),
            ("threads", "UMKM Jakarta", "@umkm_jakarta", "Pecahan kecil dari kas keliling membantu uang kembalian di warung.", False),
        ],
        "locations": ["Jakarta Timur", "Jakarta Utara", "Jakarta Pusat"],
    },
    {
        "code": "ISS-PALSU",
        "title": "Edukasi uang palsu di pasar tradisional Jakarta",
        "category": "Pengedaran Uang",
        "stance": "upside",
        "sentiment": "positif",
        "impact_level": "rendah",
        "spread_velocity": 28,
        "status": "ditinjau",
        "pic": "Analis Media",
        "is_critical": False,
        "is_kpw": True,
        "spike_detected": False,
        "day_start": 14,
        "day_end": 6,
        "has_public_figure": False,
        "summary": "KPw BI DKI mengedukasi pedagang mengenali uang palsu. Pemberitaan mendukung, dengan sedikit pertanyaan tentang temuan di lapangan.",
        "ai_what": "Program edukasi uang palsu menyasar pedagang pasar di Jakarta. Materi meliputi ciri fisik uang dan langkah bila menemukan uang mencurigakan.",
        "ai_who": "KPw BI DKI, media lokal, dan pedagang peserta.",
        "ai_sentiment": "Positif. Tidak ada lonjakan laporan uang palsu yang terbentuk sebagai isu terpisah pada data contoh ini.",
        "ai_impact": "Menekan risiko beredarnya informasi yang salah tentang ciri uang. Dampaknya preventif.",
        "ai_recommendation": "Saran komunikasi: teruskan materi visual yang mudah diunggah pedagang. Bila ada temuan kasus, pisahkan fakta kejadian dari materi edukasi agar tidak menimbulkan panik.",
        "news": [
            (
                "Pedagang Tanah Abang belajar mengenali uang palsu bersama KPw BI",
                "KPw BI DKI Jakarta melatih pedagang memeriksa uang tanpa alat yang rumit. Peserta diminta menolak jasa penukaran yang tidak resmi.",
            ),
            (
                "Edukasi uang palsu menyasar pasar di Jakarta Barat",
                "Materi mencakup uang layak edar dan kebiasaan mencatat nomor seri bila menemukan uang mencurigakan.",
            ),
            (
                "Media lokal apresiasi literasi pengedaran uang",
                "Kegiatan dinilai dekat dengan kebutuhan harian. Tidak ada angka temuan baru yang diumumkan pada acara tersebut.",
            ),
            (
                "KPw tegaskan pemeriksaan uang palsu lewat jalur resmi",
                "Masyarakat diarahkan ke kanal resmi, bukan ke akun yang menawarkan jasa cek uang berbayar.",
            ),
        ],
        "social": [
            ("instagram", "KPw BI DKI", "@kpwbi_dki", "Tiga langkah awal mengenali uang mencurigakan. Simpan dan bagikan ke kasir toko Anda.", False),
            ("x", "UMKM Jakarta", "@umkm_jakarta", "Ikut edukasi uang palsu dari KPw. Ilmunya langsung kepakai di kasir.", False),
            ("youtube", "KPw BI DKI", "@kpwbi_dki", "Rekaman singkat: apa yang dilakukan pedagang bila menerima uang yang diragukan.", False),
            ("facebook", "Warga Jakarta", "@warga_jakarta_08", "Acara uang palsu di pasar kemarin bermanfaat. Tolong jadwalnya diumumkan di lebih banyak grup warga.", False),
            ("threads", "Cek Fakta Warga", "@cekfakta_warga", "Jangan percaya gambar ciri uang palsu yang tidak ada sumbernya. Ambil materi dari kanal KPw atau BI.", False),
        ],
        "locations": ["Jakarta Pusat", "Jakarta Barat", "Jakarta Selatan"],
    },
    {
        "code": "ISS-GARUDA",
        "title": "Perkembangan Proyek Garuda dan rupiah digital",
        "category": "Sistem Pembayaran",
        "stance": "netral",
        "sentiment": "netral",
        "impact_level": "sedang",
        "spread_velocity": 44,
        "status": "baru",
        "pic": "",
        "is_critical": False,
        "is_kpw": False,
        "spike_detected": False,
        "day_start": 18,
        "day_end": 8,
        "has_public_figure": True,
        "summary": "Pemberitaan rupiah digital masih campur antara penjelasan teknologi dan spekulasi. Volume sedang, nada belum mengeras.",
        "ai_what": "Media menjelaskan status Proyek Garuda sebagai eksplorasi rupiah digital. Sebagian unggahan menyamakan proyek ini dengan aset kripto, yang tidak akurat.",
        "ai_who": "Desk teknologi media nasional, kanal edukasi, dan komentator di YouTube.",
        "ai_sentiment": "Netral. Kebingungan istilah lebih menonjol daripada penolakan.",
        "ai_impact": "Bila istilah tidak dirapikan, ruang persepsi bisa diisi spekulasi. Relevansinya ke sistem pembayaran tinggi, tetapi belum menjadi isu krisis.",
        "ai_recommendation": "Saran komunikasi: gunakan analogi yang sudah disetujui pusat, tegaskan beda rupiah digital dengan kripto, dan jangan mengumumkan jadwal terbit yang belum diputuskan.",
        "news": [
            (
                "Proyek Garuda: Bank Indonesia jelaskan arah rupiah digital",
                "Rupiah digital masih dalam tahap eksplorasi desain. Bank Indonesia menekankan bahwa proyek ini berbeda dari aset kripto dan tetap bagian dari sistem pembayaran.",
            ),
            (
                "CNBC Indonesia urai beda uang elektronik dan rupiah digital",
                "Artikel membandingkan uang elektronik yang sudah beredar dan konsep rupiah digital. Nada tulisan informatif.",
            ),
            (
                "Komentator perdebatkan kesiapan masyarakat terhadap uang digital",
                "Sebagian menilai literasi masih timpang. Tidak ada penolakan terorganisasi pada periode ini.",
            ),
            (
                "Bisnis.com: fintech tunggu kepastian desain Proyek Garuda",
                "Pelaku fintech meminta kejelasan peran, tetapi memahami bahwa desain belum final. Kartu kredit dan GPN tidak tergantikan oleh proyek ini.",
            ),
        ],
        "social": [
            ("youtube", "Kanal Ekonomi", "@kanal_ekonomi_id", "Apa itu Proyek Garuda? Kami coba jelaskan tanpa menjanjikan tanggal terbit.", False),
            ("x", "Ekonomi Terbuka", "@ekonomi_terbuka", "Tolong jangan samakan rupiah digital dengan koin spekulatif. Baca penjelasan Bank Indonesia dulu.", False),
            ("x", "Warga Jakarta", "@warga_jakarta_08", "Saya masih bingung bedanya rupiah digital dan saldo uang elektronik. Ada yang bisa ilustrasikan?", False),
            ("instagram", "KPw BI DKI", "@kpwbi_dki", "Cuplikan istilah: rupiah digital bukan kripto. Materi lengkap menyusul dari kanal pusat.", False),
            ("forum", "Komunitas Publik", "komunitas_jakarta", "Utas: kumpulkan sumber resmi Proyek Garuda. Tolong jangan tempel rumor jadwal terbit.", False),
        ],
    },
    {
        "code": "ISS-KREDIT",
        "title": "Keluhan bunga kredit dan aksi kecil di Jakarta",
        "category": "Perbankan/Kredit",
        "stance": "downside",
        "sentiment": "negatif",
        "impact_level": "sedang",
        "spread_velocity": 47,
        "status": "ditinjau",
        "pic": "Analis Media",
        "is_critical": False,
        "is_kpw": True,
        "spike_detected": False,
        "day_start": 11,
        "day_end": 3,
        "has_public_figure": False,
        "summary": "Keluhan bunga kredit UMKM dan unjuk rasa skala kecil di Jakarta dikaitkan publik dengan suku bunga acuan, meski transmisinya tidak langsung.",
        "ai_what": "Sebagian pelaku usaha dan kelompok kecil pengunjuk rasa menyampaikan keluhan bunga kredit. Media lokal meliput aksi yang berlangsung tertib.",
        "ai_who": "Peserta aksi, asosiasi usaha mikro, media lokal, dan komentar di media sosial.",
        "ai_sentiment": "Negatif terhadap biaya pinjaman. Tidak terlihat seruan kekerasan pada data contoh.",
        "ai_impact": "Persepsi dapat menyederhanakan BI-Rate sebagai penyebab tunggal bunga bank. Itu risiko narasi, bukan penilaian atas kebijakan makroprudensial.",
        "ai_recommendation": "Saran komunikasi: siapkan penjelasan transmisi suku bunga yang pendek, sebut peran bank penyalur, dan pantau apakah aksi membesar atau tetap lokal. Jangan meremehkan keluhan UMKM.",
        "news": [
            (
                "Aksi kecil di Jakarta suarakan bunga kredit yang masih berat",
                "Puluhan peserta menyampaikan keluhan bunga kredit UMKM di kawasan Jakarta Pusat. Aksi berlangsung tertib. Mereka meminta transmisi suku bunga acuan terasa di kredit usaha.",
            ),
            (
                "Kredit UMKM belum serempak turun, pelaku usaha minta kejelasan",
                "Beberapa bank sudah menyesuaikan, yang lain belum. Isu LTV dan KLM muncul di kalangan komentator properti, terpisah dari tuntutan UMKM.",
            ),
            (
                "CNN Indonesia: stabilitas sistem keuangan tetap terjaga di tengah keluhan bunga",
                "Otoritas menekankan stabilitas sistem keuangan. Keluhan yang beredar lebih kepada harga kredit daripada ketahanan bank.",
            ),
            (
                "Berita Jakarta catat aspirasi pedagang soal modal usaha",
                "Aspirasi yang tercatat: plafon yang lebih ramah, proses yang tidak berbelit, dan penjelasan mengapa bunga tidak serta-merta mengikuti BI-Rate.",
            ),
        ],
        "social": [
            ("x", "UMKM Jakarta", "@umkm_jakarta", "Bunga kredit UMKM masih berat. Kami tidak menolak bank, kami minta penjelasannya jujur dan mudah.", False),
            ("x", "Warga Jakarta", "@warga_jakarta_08", "Lihat demo kecil tadi soal bunga KPR. Apakah ini memang karena BI-Rate? Saya butuh penjelasan, bukan teriakan.", False),
            ("instagram", "Ekonomi Terbuka", "@ekonomi_terbuka", "Keluhan kredit ini wajar. Yang berbahaya kalau disamakan dengan hoaks atau digoreng jadi krisis bank.", False),
            ("facebook", "Komunitas Publik", "komunitas_jakarta", "Yang ikut aksi tadi bilang intinya bunga kredit, bukan anti lembaga. Mohon liputannya utuh.", False),
            ("youtube", "Kanal Ekonomi", "@kanal_ekonomi_id", "Kenapa bunga bank tidak selalu ikut BI-Rate? Penjelasan sepuluh menit.", False),
        ],
        "locations": ["Jakarta Pusat", "Jakarta Selatan"],
    },
]

# Berita rutin yang tidak membentuk isu. days_ago dan nada diatur di seed.
BRIEFS = [
    ("Rupiah dibuka relatif stabil pada awal pekan", "Perdagangan nilai tukar rupiah dibuka tenang. Analis menunggu data inflasi dan arah dolar global.", "netral", "Rupiah/Kurs"),
    ("Likuiditas perbankan disebut masih memadai", "Bank Indonesia menilai likuiditas cukup menopang kredit yang sehat. Tidak ada tekanan luar biasa pada stabilitas sistem keuangan.", "positif", "Perbankan/Kredit"),
    ("SRBI tetap diminati pelaku pasar", "Instrumen SRBI menarik minat pada lelang terbaru. Imbal hasil bergerak terbatas.", "positif", "Kebijakan Moneter"),
    ("Inflasi inti diperkirakan tetap landai", "Ekonom memperkirakan inflasi inti tetap terkendali. Harga pangan menjadi pengecualian di beberapa daerah.", "netral", "Inflasi"),
    ("GPN catat transaksi domestik yang stabil", "Transaksi kartu berlogo GPN bergerak stabil. Tidak ada gangguan sistem yang dilaporkan.", "positif", "Sistem Pembayaran"),
    ("Fintech diingatkan patuhi ketentuan sistem pembayaran", "Bank Indonesia mengulang kewajiban kepatuhan bagi penyelenggara. Nada pemberitaan informatif.", "netral", "Sistem Pembayaran"),
    ("Ekonomi Jakarta ditopang belanja rumah tangga", "Aktivitas ritel di pusat perbelanjaan Jakarta relatif ramai. Pelaku usaha tetap memantau daya beli.", "netral", "Ekonomi Jakarta"),
    ("KPw BI DKI buka layanan informasi publik", "Meja informasi KPw BI DKI Jakarta melayani pertanyaan masyarakat tentang penukaran uang dan kanal resmi.", "positif", "Kegiatan KPw DKI"),
]

CHANNELS = [
    ("instagram", "Edukasi QRIS di Pasar Mayestik", 9, 86000, 6400, 410, 520),
    ("instagram", "Jadwal kas keliling pekan ini", 6, 54000, 2100, 180, 260),
    ("instagram", "Ciri uang layak edar", 12, 41000, 1800, 90, 140),
    ("x", "Ringkasan keputusan BI-Rate untuk pelaku usaha Jakarta", 11, 72000, 890, 120, 640),
    ("x", "Imbauan waspada penipuan mengatasnamakan BI", 1, 110000, 1500, 340, 2100),
    ("x", "Pemantauan harga pangan bersama TPID, ini peran datanya", 2, 28000, 210, 40, 90),
    ("youtube", "Tanya jawab UMKM: QRIS dan catat untung", 4, 46000, 1900, 160, 240),
    ("youtube", "Apa yang dilakukan saat menerima uang mencurigakan", 13, 22000, 640, 48, 70),
    ("instagram", "Cuplikan literasi di Jakarta Barat", 3, 39000, 2400, 200, 180),
    ("youtube", "Beda BI-Rate dan bunga kredit, dijelaskan singkat", 8, 51000, 2200, 260, 310),
]
